### ISSUE TITLE
Small issues PR?

### ISSUE THREAD

**Issue by cameronelliott** [cocowalla/Snifter#1]
Hey Coco, thanks for writing and sharing this, it rocks! You saved me from writing it, or trying to use rawcap.exe which requires a very difficult to install .Net Framework 3.5 package.
[https://www.netresec.com/?page=RawCap](https://www.netresec.com/?page=RawCap)

Anyway, during use I noticed a small nit or two, and I wonder if you are taking PR's?

To monitor both sides of a port 8096 conversation, I had to use:  snifter -i 3 -x -24545 -y -24545

Cameron

**Comment by cocowalla** [comment]
Hi, glad you find it useful!

I still use this regularly - I realise there hasn't been much repo activity, but that's only because I consider it 'complete' for what I've needed it for.

If you've found any issues, definitely happy to take some PRs! :smile:

**Comment by cocowalla** [comment]
Hi, just wanted to check in with you on the PR you mentioned? If you don't think you're going to get round to it for a while, no worries, I can close the issue for now to keep things tidy, and your PR will be most welcome whenever you have time 👍

**Comment by cocowalla** [comment]
Resolved by #2 - thanks!
