### ISSUE TITLE
The handle is invalid.

### ISSUE THREAD

**Issue by GirkovArpa** [cocowalla/Snifter#10]
```
$ ./Snifter.App.exe --interface=8 --filename=foo.txt
```
```
Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Snifter.App.Program.Main(String[] args)

```

**Comment by cocowalla** [comment]
Hi, can you say something about your environment please? From the error message I *think* you're running from Bash on Windows, but that's a guess 😅

**Comment by GirkovArpa** [comment]
Yes, I'm running Bash as Administrator on a Windows 10 Administrator account.

**Comment by cocowalla** [comment]
I've just tried the same, but am unable to replicate this.

You're not using [psexec](https://stackoverflow.com/questions/20492535/system-io-ioexception-when-calling-system-console-windowwidth) by any chance are you?

**Comment by GirkovArpa** [comment]
I'm using [raw-socket-sniffer](https://github.com/nospaceships/raw-socket-sniffer) so I will close this.
